### ISSUE TITLE
Doesn't build using go1.12

### ISSUE THREAD

**Issue by davmaz** [danieljoos/go-wasm-examples#1]
Hi -  Very nice examples, but they won't build under 1.12. Can you steer me in the right direction to fix this?
Thanks!

**Comment by danieljoos** [comment]
Mhh... just tried with Go 1.12 on Windows 10 and it builds without problems.
Where exactly do you get the error?
Does the following compilation work for you?:

(Bash)
```
GOARCH=wasm GOOS=js go build -o test.wasm ./wasm1
```

(Windows Powershell)
```powershell
$env:GOARCH="wasm"
$env:GOOS="js"
go build -o test.wasm ./wasm1
```

**Comment by davmaz** [comment]
Yes, that works for me too. But /wasm2 is where the problems start:

# ~/WASM/DanielJoos/wasm2
wasm2/main.go:12:28: undefined: js.NewCallback


I don't see a js.NewCallback in the js package. Am I missing something?


Best,

Dave

________________________________

**Comment by danieljoos** [comment]
Ah, I was indeed only trying to compile wasm1 and wasm3.
Looking at the changelog, I found that they renamed the function:
https://golang.org/doc/go1.12#minor_library_changes
It is now called `FuncOf`. I'll adapt the examples later today.
Thanks for finding this issue.

**Comment by danieljoos** [comment]
Alright, should be fixed with e1311efb5f2b7fd05a264b0b38c2ad3110746ce5
